/*-------------------------------------------------------------------*/
/* build instruction decode table                                    */
/*-------------------------------------------------------------------*/

#include <stdio.h>
#include <stdint.h>

char instruction_type[65536];  /* maps all words to inst format type */

static void dump_struct(void);
static void dump_branch_tree(void);
static void build_decode(void);

int main(int argc,char* argv[])
{
    build_decode();
    printf( "/* no modify - generated by instruction-type-gen.c */\n\n");
    printf( "#include <stdint.h>\n\n");
    printf( "uint8_t instruction_type(uint16_t op)\n");
    printf( "{\n");
    dump_branch_tree();
    printf( "\treturn 0;\n");
    printf( "}\n");
    return 0;
}

/*-------------------------------------------------------------------*/
/* build instruction decode table                                    */
/*-------------------------------------------------------------------*/
static void build_decode(void) 
{
  int i, j;
  /* fill table with 0's (invalid opcode type) */
  for (i = 0; i < 65536; i++)
    instruction_type[i] = 0;
  /* fill format 1 part of table */
  for (i = 0; i < 16; i++)
    instruction_type[i] = 1;
  /* fill format 2 part of table */
  for (i = 16; i < 48; i++)
    instruction_type[i] = 2;
  /* fill format 3 part of table */
  for (i = 48; i < 64; i++)
    instruction_type[i] = 3;
  /* fill format 4 part of table */
  for (i = 64; i < 256; i++)
    instruction_type[i] = 4;
  /* fill format 5 part of table */
  for (i = 1; i < 8; i++)
    for (j = 0; j < 256; j++)
      instruction_type[j + (i * 256)] = 5;
  for (i = 0; i < 8; i++)
    for (j = 0; j < 256; j++)
      instruction_type[32768 + j + (i * 256)] = 5;
  /* fill format 6 (split ops) part of table */
  for (i = 8; i < 10; i++)
    for (j = 0; j < 256; j++)
      instruction_type[j + (i * 256)] = 6;
  for (i = 8; i < 10; i++)
    for (j = 0; j < 256; j++)
      instruction_type[32768 + j + (i * 256)] = 6;
  for (i = 14; i < 16; i++)
    for (j = 0; j < 256; j++)
      instruction_type[32768 + j + (i * 256)] = 6;
  /* fill format 7 part of table */
  for (i = 10; i < 14; i++)
    for (j = 0; j < 256; j++)
      instruction_type[j + (i * 256)] = 7;
  for (i = 10; i < 14; i++)
    for (j = 0; j < 256; j++)
      instruction_type[32768 + j + (i * 256)] = 7;
  /* fill format 8 part of table */
  for (i = 14; i < 16; i++)
    for (j = 0; j < 256; j++)
      instruction_type[j + (i * 256)] = 8;
  /* fill format 9 part of table */
  for (i = 112; i < 128; i++)
    for (j = 0; j < 256; j++)
      instruction_type[j + (i * 256)] = 9;
  /* fill format 10 part of table */
  for (i = 16; i < 112; i++)
    for (j = 0; j < 256; j++)
      instruction_type[j + (i * 256)] = 10;
  for (i = 16; i < 112; i++)
    for (j = 0; j < 256; j++)
      instruction_type[32768 + j + (i * 256)] = 10;
  /* fill format 11 part of table */
  for (i = 0; i < 5; i++)
    for (j = 0; j < 256; j++)
      instruction_type[61440 + j + (i * 256)] = 11;
} 

static void dump_struct(void)
{
    printf( "static const uint8_t instruction_type[] = {\n");
    for (int i = 0; i < 65536; i+=16)
    {
        printf ("\t/* %04X  */\t", i );
        for (int j = 0; j < 16; j++ )
        {
            int k = i+j;
            printf( "0x%02X,",instruction_type[k]);
        }
        printf ("\n", i );
    }
    printf( "};\n" );    
}

static void dump_branch_tree(void)
{
    uint8_t t;
    uint32_t x=0;
    uint32_t y=0;
    for( x=0; x < 65536; x++ )
    {
        t = instruction_type[x];
        printf( "\tif ( ( op >= 0x%04X ) && ", x );
        for( y=x; y < 65536 && instruction_type[y] == t; y++ );
        --y;
        printf( "( op <= 0x%04X ) )\n", y );
        printf( "\t\treturn %d;\n",t);
        x=y;
    }
}
