/* no modify - generated by instruction-type-gen.c */

#include <stdint.h>

uint8_t instruction_type(uint16_t op)
{
	if ( ( op >= 0x0000 ) && ( op <= 0x000F ) )
		return 1;
	if ( ( op >= 0x0010 ) && ( op <= 0x002F ) )
		return 2;
	if ( ( op >= 0x0030 ) && ( op <= 0x003F ) )
		return 3;
	if ( ( op >= 0x0040 ) && ( op <= 0x00FF ) )
		return 4;
	if ( ( op >= 0x0100 ) && ( op <= 0x07FF ) )
		return 5;
	if ( ( op >= 0x0800 ) && ( op <= 0x09FF ) )
		return 6;
	if ( ( op >= 0x0A00 ) && ( op <= 0x0DFF ) )
		return 7;
	if ( ( op >= 0x0E00 ) && ( op <= 0x0FFF ) )
		return 8;
	if ( ( op >= 0x1000 ) && ( op <= 0x6FFF ) )
		return 10;
	if ( ( op >= 0x7000 ) && ( op <= 0x7FFF ) )
		return 9;
	if ( ( op >= 0x8000 ) && ( op <= 0x87FF ) )
		return 5;
	if ( ( op >= 0x8800 ) && ( op <= 0x89FF ) )
		return 6;
	if ( ( op >= 0x8A00 ) && ( op <= 0x8DFF ) )
		return 7;
	if ( ( op >= 0x8E00 ) && ( op <= 0x8FFF ) )
		return 6;
	if ( ( op >= 0x9000 ) && ( op <= 0xEFFF ) )
		return 10;
	if ( ( op >= 0xF000 ) && ( op <= 0xF4FF ) )
		return 11;
	if ( ( op >= 0xF500 ) && ( op <= 0xFFFF ) )
		return 0;
	return 0;
}
